/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for libblitter
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/libblitter.h>
#include <hardware/custom.h>

#include <interfaces/libblitter.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

/****************************************************************************/

struct Library * LibBlitterBase = NULL;
static struct Library * __LibBlitterBase = NULL;

/****************************************************************************/

void libblitter_base_constructor(void)
{
    if (LibBlitterBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __LibBlitterBase = LibBlitterBase = IExec->OpenLibrary("libblitter.library", 0);
    if (LibBlitterBase == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to open 'libblitter.library'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzz"))) static void
(*libblitter_base_constructor_ptr)(void) USED = libblitter_base_constructor;

/****************************************************************************/

void libblitter_base_destructor(void)
{
    if (__LibBlitterBase != NULL)
    {
        IExec->CloseLibrary(__LibBlitterBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*libblitter_base_destructor_ptr)(void) USED = libblitter_base_destructor;

/****************************************************************************/

