/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for libblitter
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/libblitter.h>
#include <hardware/custom.h>

#include <interfaces/libblitter.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

struct LibBlitterIFace * ILibBlitter = NULL;
static struct Library * __LibBlitterBase = NULL;
static struct LibBlitterIFace * __ILibBlitter = NULL;

/****************************************************************************/

extern struct Library * LibBlitterBase;

/****************************************************************************/

void libblitter_main_constructor(void)
{
    if (ILibBlitter != NULL)
    {
        return; /* Someone was quicker */
    }
    if (LibBlitterBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __LibBlitterBase = LibBlitterBase = IExec->OpenLibrary("libblitter.library", 0);
        if (LibBlitterBase == NULL)
        {
            IDOS->PutErrStr("ERROR: Failed to open 'libblitter.library'.\n");
            abort();
        }
    }

    __ILibBlitter = ILibBlitter = (struct LibBlitterIFace *)IExec->GetInterface((struct Library *)LibBlitterBase, "main", 1, NULL);
    if (ILibBlitter == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to get 'main' V1 interface for 'libblitter.library'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzy"))) static void
(*libblitter_main_constructor_ptr)(void) USED = libblitter_main_constructor;

/****************************************************************************/

void libblitter_main_destructor(void)
{
    if (__ILibBlitter)
    {
        IExec->DropInterface ((struct Interface *)__ILibBlitter);
    }
    if (__LibBlitterBase)
    {
        IExec->CloseLibrary(__LibBlitterBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*libblitter_main_destructor_ptr)(void) USED = libblitter_main_destructor;

/****************************************************************************/

