
/* This file was generated by idltool 53.35. Do not edit */

#include "libblitter_vectors.h"

STATIC uint32 VARARGS68K _libblitter_UNIMPLEMENTED(struct LibBlitterIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _libblitter_Obtain,
    _libblitter_Release,
    _libblitter_UNIMPLEMENTED, /* Expunge */
    _libblitter_UNIMPLEMENTED, /* Clone */
    _libblitter_BLTSIZH,
    _libblitter_BLTSIZE,
    (APTR)-1
};
