#ifndef LIBBLITTER_INTERFACE_DEF_H
#define LIBBLITTER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.35.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_LIBBLITTER_H
#include <libraries/libblitter.h>
#endif
#ifndef HARDWARE_CUSTOM_H
#include <hardware/custom.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct LibBlitterIFace
{
	struct InterfaceData Data;

	APICALL ULONG (*Obtain)(struct LibBlitterIFace *Self);
	APICALL ULONG (*Release)(struct LibBlitterIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	APICALL void (*BLTSIZH)(struct LibBlitterIFace *Self, struct Custom * custom);
	APICALL void (*BLTSIZE)(struct LibBlitterIFace *Self, struct Custom * custom);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* LIBBLITTER_INTERFACE_DEF_H */
